# Generated by Django 4.2.11 on 2024-06-28 03:54

from django.db import migrations

def populate_destinations(apps, schema_editor):
    Destination = apps.get_model('main', 'Destination')
    destinations = [
        {"name": "New York City", "description": "The Big Apple", "location": "New York"},
        {"name": "Los Angeles", "description": "The City of Angels", "location": "California"},
        {"name": "Chicago", "description": "The Windy City", "location": "Illinois"},
        {"name": "Houston", "description": "Space City", "location": "Texas"},
        {"name": "Phoenix", "description": "The Valley of the Sun", "location": "Arizona"},
        {"name": "Philadelphia", "description": "The City of Brotherly Love", "location": "Pennsylvania"},
        {"name": "San Antonio", "description": "Alamo City", "location": "Texas"},
        {"name": "San Diego", "description": "America's Finest City", "location": "California"},
        {"name": "Dallas", "description": "Big D", "location": "Texas"},
        {"name": "San Jose", "description": "The Capital of Silicon Valley", "location": "California"},
        {"name": "Austin", "description": "Live Music Capital of the World", "location": "Texas"},
        {"name": "Jacksonville", "description": "River City", "location": "Florida"},
        {"name": "Fort Worth", "description": "Cowtown", "location": "Texas"},
        {"name": "Columbus", "description": "The Arch City", "location": "Ohio"},
        {"name": "Charlotte", "description": "The Queen City", "location": "North Carolina"},
        {"name": "San Francisco", "description": "The Golden City", "location": "California"},
        {"name": "Indianapolis", "description": "The Circle City", "location": "Indiana"},
        {"name": "Seattle", "description": "Emerald City", "location": "Washington"},
        {"name": "Denver", "description": "The Mile High City", "location": "Colorado"},
        {"name": "Washington D.C.", "description": "The Capital", "location": "District of Columbia"},
        {"name": "Boston", "description": "Beantown", "location": "Massachusetts"},
        {"name": "El Paso", "description": "The Sun City", "location": "Texas"},
        {"name": "Nashville", "description": "Music City", "location": "Tennessee"},
        {"name": "Detroit", "description": "Motor City", "location": "Michigan"},
        {"name": "Oklahoma City", "description": "The Big Friendly", "location": "Oklahoma"},
        {"name": "Portland", "description": "The Rose City", "location": "Oregon"},
        {"name": "Las Vegas", "description": "Sin City", "location": "Nevada"},
        {"name": "Memphis", "description": "Home of the Blues", "location": "Tennessee"},
        {"name": "Louisville", "description": "Derby City", "location": "Kentucky"},
        {"name": "Baltimore", "description": "Charm City", "location": "Maryland"},
    ]

    for destination in destinations:
        Destination.objects.create(**destination)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_destinations),
    ]
